-- Daktilo V14: Supabase schema
-- Run this once in the Supabase SQL Editor.

create table if not exists public.daktilo_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  challenge_points bigint not null default 0,
  training_words bigint not null default 0,
  total_words bigint not null default 0,
  total_correct bigint not null default 0,
  total_replays bigint not null default 0,
  training_ms bigint not null default 0,
  best_challenge_word bigint not null default 0,
  best_streak integer not null default 0,
  best_threshold_ms numeric,
  last_threshold_ms numeric,
  adaptive_level integer not null default 4,
  week_key text,
  week_points bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists daktilo_profiles_username_lower_idx
  on public.daktilo_profiles (lower(username));

create table if not exists public.daktilo_private_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.daktilo_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null unique,
  created_at timestamptz not null default now(),
  event jsonb not null
);

create index if not exists daktilo_events_user_created_idx
  on public.daktilo_events (user_id, created_at desc);

alter table public.daktilo_profiles enable row level security;
alter table public.daktilo_private_state enable row level security;
alter table public.daktilo_events enable row level security;

-- Public leaderboard: only aggregate profile fields live in this table.
drop policy if exists "daktilo profiles public read" on public.daktilo_profiles;
create policy "daktilo profiles public read"
  on public.daktilo_profiles for select
  to anon, authenticated
  using (true);

drop policy if exists "daktilo profiles own insert" on public.daktilo_profiles;
create policy "daktilo profiles own insert"
  on public.daktilo_profiles for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "daktilo profiles own update" on public.daktilo_profiles;
create policy "daktilo profiles own update"
  on public.daktilo_profiles for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Detailed learning state is private to the signed-in user.
drop policy if exists "daktilo private own select" on public.daktilo_private_state;
create policy "daktilo private own select"
  on public.daktilo_private_state for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "daktilo private own insert" on public.daktilo_private_state;
create policy "daktilo private own insert"
  on public.daktilo_private_state for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "daktilo private own update" on public.daktilo_private_state;
create policy "daktilo private own update"
  on public.daktilo_private_state for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Per-word events are also private; they support personal word/error statistics across devices.
drop policy if exists "daktilo events own select" on public.daktilo_events;
create policy "daktilo events own select"
  on public.daktilo_events for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "daktilo events own insert" on public.daktilo_events;
create policy "daktilo events own insert"
  on public.daktilo_events for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "daktilo events own update" on public.daktilo_events;
create policy "daktilo events own update"
  on public.daktilo_events for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Least-privilege Data API grants. RLS still controls individual rows.
grant select on public.daktilo_profiles to anon, authenticated;
grant insert, update on public.daktilo_profiles to authenticated;
grant select, insert, update on public.daktilo_private_state to authenticated;
grant select, insert, update on public.daktilo_events to authenticated;
grant usage, select on sequence public.daktilo_events_id_seq to authenticated;

-- Username-only login gateway (server-side only; no Data API access for browsers).
create table if not exists public.daktilo_username_accounts (
  username_key text primary key,
  username text not null,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  login_email text not null unique,
  created_at timestamptz not null default now()
);
alter table public.daktilo_username_accounts enable row level security;
revoke all on table public.daktilo_username_accounts from anon, authenticated;
create index if not exists daktilo_username_accounts_user_idx
  on public.daktilo_username_accounts (user_id);

-- Lightweight server-side throttling data for username auth.
create table if not exists public.daktilo_auth_attempts (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  kind text not null,
  created_at timestamptz not null default now()
);
create index if not exists daktilo_auth_attempts_lookup_idx
  on public.daktilo_auth_attempts (key_hash, kind, created_at desc);
alter table public.daktilo_auth_attempts enable row level security;
revoke all on table public.daktilo_auth_attempts from anon, authenticated;
